# -*- coding: utf-8 -*-
"""casasnovas_Lab5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HL7lQMzxupbOKp3tVVYDibroe-o_77Zs
"""

import random
scores = []

for i in range(10):
  number = random.randint(0,100)
  scores.append(number)

print("Before replacement:", scores)

average = sum(scores) / len(scores)
print("Average score:", average)
lowest = min(scores)
print("Lowest score:", lowest)
highest = max(scores)
print("Highest score:", highest)

print(" ")


lowest = min(scores)
highest = max(scores)

pos = scores.index(lowest)


scores[pos] = highest


print("The lowest score", lowest, "was replaced with the highest score", highest)


print("After replacement:", scores)

new_average = sum(scores) / len(scores)
print("New average score:", new_average)

print(" ")


random_choice = random.choice(scores)
print("Randomly selected score:", random_choice)


sample_scores = random.sample(scores, 3)
print("Random sample:", sample_scores)

scores.sort()
print("Sorted:", scores)

random.shuffle(scores)
print("Shuffled:", scores)
print(" ")

print("Individual scores and their dispersion:")

for i in scores:
    print(f"{i} : distance from average: {abs(new_average - i):.1f}")

